<?php

/**
 * Push contact to procurios.
 */

/**
 * Implements hook_init().
 */
function procpush_init() {
  module_load_include("inc", "procpush", "procpush");
}

/**
 * Data fields to be passed to procpush_push_contact($data).
 *
 * selections => array(
 *   'add' => array(),
 *   'remove' => array(),
 * )
 *
 * sp_active => array(
 *   active,
 *   activities: array()
 * )
 *
 * sp_work_and_int => array(
 *   main_task: array(),
 *   industrial_sector,
 *   occupational_group ,
 * )
 *
 */
function procpush_data_fields() {
  $data_fields = array(
    'relation_id' =>  array(
      'title' => 'Relatienummer',
      'type' => 'string',
    ),
    'overwrite' =>  array(
      'title' => 'Overschrijven',
      'type' => 'boolean',
    ),
    'name' =>  array(
      'title' => 'Gehele naam',
      'type' => 'string',
    ),
    'first_name' =>  array(
      'title' => 'Voornaam',
      'type' => 'string',
    ),
    'middle_name' =>  array(
      'title' => 'Tussenvoegsel',
      'type' => 'string',
    ),
    'last_name' =>  array(
      'title' => 'Achternaam',
      'type' => 'string',
    ),
    'email' =>  array(
      'title' => 'E-mail',
      'type' => 'string',
    ),
    'phone' =>  array(
      'title' => 'Telefoon',
      'type' => 'string',
    ),
    'fixed_phone' =>  array(
      'title' => 'Telefoon vast',
      'type' => 'string',
    ),
    'mobile_phone' =>  array(
      'title' => 'Telefoon mobiel',
      'type' => 'string',
    ),
    'fixed_phone_work' =>  array(
      'title' => 'Telefoon vast werk',
      'type' => 'string',
    ),
    'mobile_phone_work' =>  array(
      'title' => 'Telefoon mobiel werk',
      'type' => 'string',
    ),
    'street' =>  array(
      'title' => 'Straat',
      'type' => 'string',
    ),
    'house_number_and_addition' =>  array(
      'title' => 'Huisnummer inclusief eventuele toevoeging',
      'type' => 'string',
    ),
    'house_number' =>  array(
      'title' => 'Huisnummer',
      'type' => 'string',
    ),
    'house_number_addition' =>  array(
      'title' => 'Huisnummer toevoeging',
      'type' => 'string',
    ),
    'postal_code' =>  array(
      'title' => 'Postcode',
      'type' => 'string',
    ),
    'locality' =>  array(
      'title' => 'Plaats',
      'type' => 'string',
    ),
    'selections' =>  array(
      'title' => 'Selecties',
      'type' => 'array',
    ),
    'sp_active' =>  array(
      'title' => 'Actief SP',
      'type' => 'array',
    ),
    'sp_work_and_int' =>  array(
      'title' => 'Werk en interesses',
      'type' => 'array',
    ),
    'privacy' =>  array(
      'title' => 'Privacy',
      'type' => 'array',
    ),
  );
  return $data_fields;
}

/**
 * Push contact to procurios.
 */
function procpush_push_contact($data, $debug_info = NULL) {
  $error = FALSE;
  // Check if testing.
  if (
    (!empty($data['name']) && strpos(strtolower($data['name']), '-test') !== FALSE) ||
    (!empty($data['first_name']) && strpos(strtolower($data['first_name']), '-test') !== FALSE) ||
    (!empty($data['last_name']) && strpos(strtolower($data['last_name']), '-test') !== FALSE)
  ) {
    drupal_set_message('Test data, not sending to CiviCRM');
    return 'test data';
  }

  // Fix data for Procurios.
  $data = procpush_fix_data($data);

  // Check if sufficient data.
  if (procpush_check_submission_sufficient($data)) {
    // Check if existing or new contact.
    if (empty($data['relation_id'])) {
      if ($relation_id = procpush_push_new_contact($data, $debug_info)) {
        return $relation_id;
      }
    }
    else {
      if (procpush_push_existing_contact($data, $debug_info)) {
        return $data['relation_id'];
      }
    }
  }
  else {
    $debug_info['push_contact_submission_check'] = 'Insufficient data.';
  }

  // An error occurred.
  $error_message = 'Er is een fout opgetreden bij het pushen van contact data naar Procurios.';
  procpush_error($error_message, $debug_info);
  return FALSE;
}

/**
 * Implements hook_menu().
 * @return array Menu items
 */

function procpush_menu() {
  $items = array();

  $items['admin/config/sp/procpush'] = array(
    'title' => 'Procurios Push',
    'page callback'  => 'drupal_get_form',
    'page arguments' => array('procpush_settings_form'),
    'access callback' => 'sprbs_access_check',
    'file' => 'procpush.admin.inc',
  );

  $items['admin/config/sp/procpush/settings'] = array(
    'title' => 'Instellingen',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access callback' => 'sprbs_access_check',
  );

  $items['admin/config/sp/procpush/test'] = array(
    'title' => 'Test',
    'type' => MENU_LOCAL_TASK,
    'page callback'  => 'drupal_get_form',
    'page arguments' => array('procpush_test_form'),
    'file' => 'procpush.test.inc',
    'access callback' => 'sprbs_access_check',
  );

  return $items;
}
